[metadata]
name = la-dev-codex-plugins
version = 0.4.1
description = Language-agnostic development Codex plugins.
long_description = file: PYPI.md
long_description_content_type = text/markdown
author = pallgeuer
url = https://github.com/pallgeuer/la-dev-codex-plugins
license = MIT
license_files = LICENSE
project_urls =
    Documentation = https://github.com/pallgeuer/la-dev-codex-plugins#readme
    Issues = https://github.com/pallgeuer/la-dev-codex-plugins/issues
    Source = https://github.com/pallgeuer/la-dev-codex-plugins
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Console
    Operating System :: MacOS
    Operating System :: POSIX
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
install_requires =
scripts =
    package_scripts/codex-perform

[options.entry_points]
console_scripts =
    la-dev-markdown-tables = la_dev_codex_plugins.markdown_tables.cli:main
    la-dev-release-checksums = la_dev_codex_plugins.release_checksums.cli:main

[options.extras_require]
pytest =
    pytest>=7.0.1
dev =
    pytest>=7.0.1

[options.packages.find]
where = src
