[metadata]
name = la-dev-codex-plugins
version = 0.2.0
description = Language-agnostic development Codex plugins.
long_description = file: README.md
long_description_content_type = text/markdown
author = pallgeuer
url = https://github.com/pallgeuer/la-dev-codex-plugins
license = MIT

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
install_requires =

[options.packages.find]
where = src
