"""Perform catalog discovery and rendering runtime."""

from .api import (
    compact_json,
    diagnostic_strings,
    error_exit_code,
    error_payload,
    merge_response_payload,
    response_payload,
)
from .catalog import (
    ACTION_FIELDS,
    ACTION_NAME_PATTERN,
    ACTION_NAME_REGEX,
    EFFORT_REGEX,
    HELP_GLOSS,
    HELP_SELECTOR,
    LANGUAGE_NAME_PATTERN,
    LANGUAGE_NAME_REGEX,
    MODEL_REGEX,
    PLACEHOLDER_REGEX,
    STRICT_SELECTOR_PATTERN,
    ActionCatalog,
    ActionInspection,
    ActionSummary,
    BuiltInHelpResult,
    CatalogRequestError,
    DuplicateKeyError,
    EffectiveAction,
    RenderedAction,
    is_action_name,
    load_action_catalog,
    loads_unique_json,
    parse_selector,
)
from .cli import CliContext, CliOutcome, JsonArgumentParser, bundled_actions_dir, emit_json, encode_json, run_cli
from .discovery import DiscoveryResult, FilesystemView, GitCommandResult, SourceDirectory, discover_action_directories, explicit_discovery, run_bounded_git_root

__all__ = (
    "ACTION_FIELDS",
    "ACTION_NAME_PATTERN",
    "ACTION_NAME_REGEX",
    "EFFORT_REGEX",
    "HELP_GLOSS",
    "HELP_SELECTOR",
    "LANGUAGE_NAME_PATTERN",
    "LANGUAGE_NAME_REGEX",
    "MODEL_REGEX",
    "PLACEHOLDER_REGEX",
    "STRICT_SELECTOR_PATTERN",
    "ActionCatalog",
    "ActionInspection",
    "ActionSummary",
    "BuiltInHelpResult",
    "CatalogRequestError",
    "CliContext",
    "CliOutcome",
    "DiscoveryResult",
    "DuplicateKeyError",
    "EffectiveAction",
    "FilesystemView",
    "GitCommandResult",
    "JsonArgumentParser",
    "RenderedAction",
    "SourceDirectory",
    "bundled_actions_dir",
    "compact_json",
    "diagnostic_strings",
    "discover_action_directories",
    "emit_json",
    "encode_json",
    "error_exit_code",
    "error_payload",
    "explicit_discovery",
    "is_action_name",
    "load_action_catalog",
    "loads_unique_json",
    "merge_response_payload",
    "parse_selector",
    "response_payload",
    "run_bounded_git_root",
    "run_cli",
)
